import operator
from typing import Annotated, List, Dict, Any, TypedDict

class FinancialState(TypedDict):
    # Inputs
    ticker: str
    
    # 1. Data Ingestion Agent Output
    start_date: str
    end_date: str
    # Storing dataframe as a JSON string or dict to keep it serializable for the graph
    # (In practice, passing the DF directly works in-memory, but let's keep it flexible)
    historical_data: Annotated[Any, "The raw dataframe or list of dicts"] 
    
    # 2. Fundamental & Technical Agent Output
    # Basic metrics like P/E, Market Cap
    fundamental_metrics: Dict[str, Any]
    # Technical signals (RSI, MACD values)
    technical_indicators: Dict[str, Any]
    
    # 3. Risk Agent Output
    risk_metrics: Dict[str, Any]  # e.g., {'max_drawdown': -0.20, 'sharpe_ratio': 1.5}
    
    # 4. Synthesis Agent Output
    recommendation: str  # "Buy", "Sell", or "Hold"
    final_report: str    # The full explanation generated by Gemini